apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

namespace: app1-dev

patches:
- target:
    kind: Deployment
    name: app1
  patch: |-
    - op: ensure
      path: /spec/template/spec/imagePullSecrets
      value: []
    - op: add
      path: /spec/template/spec/imagePullSecrets/-
      value:
        name: github-registry-secret

configMapGenerator:
- name: app1-config
  behavior: merge
  literals:
  - ENVIRONMENT=dev
  - LOG_LEVEL=DEBUG

# Add this section to pull the GitHub Container Registry secret
secretGenerator:
- name: github-registry-secret
  namespace: app1-dev
  type: kubernetes.io/dockerconfigjson
  behavior: replace