apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

namespace: app1-dev

patches:
- target:
    kind: Deployment
    name: app1
  patch: |-
    - op: replace
      path: /spec/template/spec/imagePullSecrets
      value:
      - name: github-registry-secret

configMapGenerator:
- name: app1-config
  behavior: merge
  literals:
  - ENVIRONMENT=dev
  - LOG_LEVEL=DEBUG