# infrastructure-repo/infrastructure/monitoring/base/helm-values.yaml
# Values for kube-prometheus-stack
# Reference: https://github.com/prometheus-community/helm-charts/blob/main/charts/kube-prometheus-stack/values.yaml

global:
  evaluation_interval: 1m

prometheusOperator:
  createCustomResource: true

prometheus:
  enabled: true
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    ruleSelector: {}
    retention: 10d
    enableAdminAPI: false
    walCompression: true
    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['job']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: 'null'
      routes:
      - match:
          alertname: Watchdog
        receiver: 'null'
    receivers:
    - name: 'null'
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

grafana:
  enabled: true
  adminPassword: "gitops-admin"  # Change for production
  persistence:
    enabled: true
    size: 5Gi
  dashboardProviders:
    dashboardproviders.yaml:
      apiVersion: 1
      providers:
        - name: default
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        revision: 1
        datasource: Prometheus
      gitops-metrics:
        gnetId: 13621  # ArgoCD/GitOps dashboard
        revision: 1
        datasource: Prometheus
      node-exporter:
        gnetId: 1860  # Node Exporter dashboard
        revision: 22
        datasource: Prometheus

nodeExporter:
  enabled: true

kubeStateMetrics:
  enabled: true

# For development environments, reduce resource requirements
resources:
  limits:
    cpu: 200m
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi