# infrastructure-repo/apps/external-app1/overlays/prod/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-app1
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  tls:
  - hosts:
    - external-app1.gitops.local
    - www.external-app1.gitops.local
    secretName: external-app1-prod-tls
  rules:
  - host: external-app1.gitops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-app1
            port:
              name: http
  - host: www.external-app1.gitops.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: external-app1
            port:
              name: http
