apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml

namespace: app1-prod

patches:
- path: patches.yaml
  target:
    kind: Deployment
    name: app1

configMapGenerator:
- name: app1-config
  behavior: merge
  literals:
  - ENVIRONMENT=prod
  - LOG_LEVEL=WARN

# Add this section to pull the GitHub Container Registry secret
secretGenerator:
- name: github-registry-secret
  namespace: app1-prod
  type: kubernetes.io/dockerconfigjson
  behavior: replace