apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: app1
        env:
        - name: ENVIRONMENT
          value: "production"
        - name: LOG_LEVEL
          value: "warn"
        resources:
          limits:
            memory: "512Mi"
            cpu: "1000m"
          requests:
            memory: "256Mi"
            cpu: "500m"