apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-config
data:
  app.properties: |
    logging.level=INFO
    feature.experimental=false
    cache.timeout=300
  
  # Environment variables
  CACHE_HOST: "redis.default.svc.cluster.local"
  CACHE_PORT: "6379"