# config-repo/apps/app1/base/service-monitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: app1
  labels:
    app: app1
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: app1
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
