apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Environment-specific configuration for qa
configMapGenerator:
- name: ingress-nginx-values
  files:
  - values.yaml=values-override.yaml