apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- prometheus-rules.yaml

# Note: The actual kube-prometheus-stack deployment is handled by Helm in the GitHub Actions workflow,
# so we don't include the helm-values.yaml file here as a resource.
# This kustomization only includes resources that will be applied directly with kubectl.

commonLabels:
  app.kubernetes.io/part-of: monitoring-stack
  app.kubernetes.io/managed-by: gitops

# Allows the resources to be referenced from overlay directories
namePrefix: ""