apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

namespace: external-app2

images:
- name: ghcr.io/triplom/external-app2
  newTag: latest

commonLabels:
  app: external-app2
  component: web
