apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# Environment-specific configuration
patchesJson6902:
- target:
    group: cert-manager.io
    version: v1
    kind: ClusterIssuer
    name: letsencrypt-prod
  patch: |
    - op: replace
      path: /spec/acme/email
      value: prod-admin@gitops.local