# infrastructure-repo/kind/clusters/qa-cluster-config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: qa-cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31000
    hostPort: 31000
    protocol: TCP
  - containerPort: 31001
    hostPort: 31001
    protocol: TCP
  - containerPort: 31002
    hostPort: 31002
    protocol: TCP
  - containerPort: 80
    hostPort: 9080
    protocol: TCP
  - containerPort: 443
    hostPort: 9443
    protocol: TCP
- role: worker
- role: worker
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6444